### ISSUE TITLE
Implement predict_proba

### ISSUE THREAD

**Issue by PedroFerreiradaCosta** [Mind-the-Pineapple/sklearn-rvm#13]
Need to implement predict_proba in order to run predict for the RVC.

**Comment by PedroFerreiradaCosta** [comment]
Added on aef051692e908e7b3c82540a5e29a7907d5dc350. Need testing

**Comment by Warvito** [comment]
There is a bug on predict_proba when I tried to run simple_example.py

When we directly call print(clf.predict_proba(X)) it do not add the bias element. So we get this error

ValueError                                Traceback (most recent call last)
<ipython-input-25-5020670975c6> in <module>
     14 
     15 print(clf.predict(X))
---> 16 print(clf.predict_proba(X))
     17 print(clf.score(X, y))

<ipython-input-19-ec21763359c8> in predict_proba(self, Phi_)
    735     def predict_proba(self, Phi_):
    736         """Return an array of class probabilities."""
--> 737         y = self._classify(self.mu_, Phi_)
    738         return np.column_stack((1 - y, y))
    739 

<ipython-input-19-ec21763359c8> in _classify(self, mu, Phi_)
    526     def _classify(self, mu, Phi_):
    527         """ Perform Sigmoid Classification."""
--> 528         return expit(np.dot(Phi_, mu))
    529 
    530     def _log_posterior(self, mu, alpha, Phi_, t):

<__array_function__ internals> in dot(*args, **kwargs)

ValueError: shapes (100,1) and (101,) not aligned: 1 (dim 1) != 101 (dim 0)

It is necessary figure out how to deal with it. I will try to find a solution on the sklearn repository. I will update here any progress

**Comment by Warvito** [comment]
I did not find a similar case on sklearn.
I tried to simplify the problem by removing the return_std.

Proposed solution in 60c124093ba0c0237d6399e24a6aeb5601df5d21

I will test on a multi-classes example too.

**Comment by Warvito** [comment]
I replaced the multiclass.OneVsOneClassifier to multiclass.OneVsRestClassifier to be able to use its predict_proba. daebb3e4b260c3c11583e8f1ff58b513e0252348

Besides, I added a simple test for multiclass 8fddd934616d31dacd4b8ccd88aa4da3b7db4ac6

I will check if the code works for  precomputed kernels now.

**Comment by Warvito** [comment]
The precomputed kernel work for binary case but I am getting this problem on multi-class case

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/media/kcl_1/HDD/PycharmProjects/sklearn-rvm/venv/lib/python3.6/site-packages/sklearn/multiclass.py in _predict_binary(estimator, X)
     93     try:
---> 94         score = np.ravel(estimator.decision_function(X))
     95     except (AttributeError, NotImplementedError):

AttributeError: 'EMRVC' object has no attribute 'decision_function'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-69-de76b6ad2517> in <module>
      1 
      2 K_test = pairwise_kernels(X_test, X_train)
----> 3 print(clf.predict(K_test))
      4 print(clf.predict_proba(K_test))
      5 print(clf.score(K_test, y_test))

<ipython-input-49-630f3c4471d6> in predict(self, X)
    782 
    783         else:
--> 784             return self.multi_.predict(X)

/media/kcl_1/HDD/PycharmProjects/sklearn-rvm/venv/lib/python3.6/site-packages/sklearn/multiclass.py in predict(self, X)
    318             argmaxima = np.zeros(n_samples, dtype=int)
    319             for i, e in enumerate(self.estimators_):
--> 320                 pred = _predict_binary(e, X)
    321                 np.maximum(maxima, pred, out=maxima)
    322                 argmaxima[maxima == pred] = i

/media/kcl_1/HDD/PycharmProjects/sklearn-rvm/venv/lib/python3.6/site-packages/sklearn/multiclass.py in _predict_binary(estimator, X)
     95     except (AttributeError, NotImplementedError):
     96         # probabilities of the positive class
---> 97         score = estimator.predict_proba(X)[:, 1]
     98     return score
     99 

<ipython-input-49-630f3c4471d6> in predict_proba(self, X)
    738 
    739         if len(self.classes_) == 2:
--> 740             K = self._get_kernel(X, self.relevance_vectors_)
    741             X = check_array(X)
    742 

<ipython-input-49-630f3c4471d6> in _get_kernel(self, X, Y)
     60                       "coef0": self.coef0}
     61             return pairwise_kernels(X, Y, metric=self.kernel,
---> 62                                     filter_params=True, **params)
     63 
     64     def _prune(self):

/media/kcl_1/HDD/PycharmProjects/sklearn-rvm/venv/lib/python3.6/site-packages/sklearn/metrics/pairwise.py in pairwise_kernels(X, Y, metric, filter_params, n_jobs, **kwds)
   1893 
   1894     if metric == "precomputed":
-> 1895         X, _ = check_pairwise_arrays(X, Y, precomputed=True)
   1896         return X
   1897     elif isinstance(metric, GPKernel):

/media/kcl_1/HDD/PycharmProjects/sklearn-rvm/venv/lib/python3.6/site-packages/sklearn/metrics/pairwise.py in check_pairwise_arrays(X, Y, precomputed, dtype, accept_sparse, force_all_finite, copy)
    149                              "(n_queries, n_indexed). Got (%d, %d) "
    150                              "for %d indexed." %
--> 151                              (X.shape[0], X.shape[1], Y.shape[0]))
    152     elif X.shape[1] != Y.shape[1]:
    153         raise ValueError("Incompatible dimension for X and Y matrices: "

ValueError: Precomputed metric requires shape (n_queries, n_indexed). Got (38, 112) for 38 indexed.
