### ISSUE TITLE
can it be used for categorical data classier for binary target?

### ISSUE THREAD

**Issue by Sandy4321** [Mind-the-Pineapple/sklearn-rvm#19]
can it be used for categorical data classier for binary target?
 
since there is example for continues data ?

or categorical data should be transformed to one hot data?

**Comment by PedroFerreiradaCosta** [comment]
It can be used for categorical data. Both categorical data and one-hot data will work fine.
Pedro

**Comment by Sandy4321** [comment]
"categorical data  will work fine"
great news
do you mean I can feed to your code mixture of categorical data and continues data and code will work correctly ?
so categorical data will be transformed for one hot automatically ?

**Comment by PedroFerreiradaCosta** [comment]
Ah, do you mean pass categorical data as input for the model? In that case, no, it has to be transformed into a one-hot vector. The target though can be categorical and the model's prediction will also be categorical in that case.
