### ISSUE TITLE
which kernel is the best  for unbalanced  one hot  data for classifier?

### ISSUE THREAD

**Issue by Sandy4321** [Mind-the-Pineapple/sklearn-rvm#21]
which kernel is the best  for unbalanced  one hot  data for classifier?
for one hot data: only 0s and 1s in data

**Comment by PedroFerreiradaCosta** [comment]
I don't think there is a kernel that always performs better than others on unbalanced data. It will depend on the complexity of your data.
If these kernels don't work properly for your problem, you can treat it instead as an anomaly detection problem or use a library like https://imbalanced-learn.readthedocs.io/en/stable/
Pedro
