### ISSUE TITLE
how to control level of sparsity?

### ISSUE THREAD

**Issue by Sandy4321** [Mind-the-Pineapple/sklearn-rvm#22]
how to control level of sparsity?

**Comment by PedroFerreiradaCosta** [comment]
Level of sparsity can be controlled with the 'threshold_alpha' parameter which defines the cut-off value of the basis functions. Set it to a higher level to have less sparsity and to a lower level to obtain more sparsity. Default is 1e5 but it will be changed to 1e9 in v0.1.1

**Comment by PedroFerreiradaCosta** [comment]
I should also say that higher values of 'threshold_alpha' will result in longer training times as less basis functions are pruned.
