### ISSUE TITLE
Regressor model with only bias (no relevant vectors)

### ISSUE THREAD

**Issue by Warvito** [Mind-the-Pineapple/sklearn-rvm#4]
Using the EMRVR method, some models after training have only the bias on phi. 
This make not possible to perform predictions of unseen data.

This problem might be due to the inversion of the matrix hessian.

**Comment by Warvito** [comment]
Looks like Cholesky decomposition solved the problem since it is easier to find the inverse of a triangular matrix than the original one.

**Comment by Warvito** [comment]
One thing that I notice is that the models' performance is more stable now. Before, some sessions showed really bad performance.
I think this is a great sign for our tool compared with the previous implementations.

@PedroFerreiradaCosta Could please try to train brain age models using this new implementation?

**Comment by Warvito** [comment]
Bad news, I am getting this problem now

---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-5-0305f2af5c4f> in <module>
     54         # Systematic search for best hyperparameters
     55         rvm = EMRVR(kernel='linear')
---> 56         rvm.fit(x_train, y_train)
     57         predictions = rvm.predict(x_test)
     58 

<ipython-input-1-28e6253bf355> in fit(self, X, y)
    222             # Use Cholesky decomposition for efficiency
    223             # Ref: https://arxiv.org/abs/1111.4144
--> 224             upper = scipy.linalg.cholesky(hessian)
    225             try:
    226                 upper_inv = np.linalg.inv(upper)

/media/kcl_1/HDD/PycharmProjects/predicted_brain_age/venv/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py in cholesky(a, lower, overwrite_a, check_finite)
     89     """
     90     c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
---> 91                          check_finite=check_finite)
     92     return c
     93 

/media/kcl_1/HDD/PycharmProjects/predicted_brain_age/venv/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py in _cholesky(a, lower, overwrite_a, clean, check_finite)
     38     if info > 0:
     39         raise LinAlgError("%d-th leading minor of the array is not positive "
---> 40                           "definite" % info)
     41     if info < 0:
     42         raise ValueError('LAPACK reported an illegal value in {}-th argument'

LinAlgError: 24-th leading minor of the array is not positive definite

**Comment by Warvito** [comment]
As suggested in the link below, we could try other kind of decomposition.

https://stackoverflow.com/questions/21604498/numpy-cholesky-decomposition-linalgerror

**Comment by Warvito** [comment]
I added a temporary solution, where we calculate the inverse without the Cholesky decomposition, in case of a  not positive definite hessian matrix. 19726fe2cc547e97053008b93d971698ab8d7bdd

**Comment by Warvito** [comment]
Even with the previous approaches, there is some cases that the result is a model without relevant vectors.

It is necessary to figure out how to deal with it before merge (for example, print some warning)

**Comment by Warvito** [comment]
@PedroFerreiradaCosta There is a error on the normalization of the kernel. It is not exactly equal to Pronto implementation.

In pronto they squared element wise before scale it:

```
scale             = sqrt(sum(sum(Phi(1:N,1:N).^2))/N^2);
scale             = [ones(N,1)*scale ; 1];
```

Maybe it will reduce even more the magnitude of the numbers and improve the results. We should try later and evaluate the best method.

**Comment by Warvito** [comment]
@PedroFerreiradaCosta I added an epsilon to the code to try improve the numerical stability aed5cbeb8e39169c78ecff2b4d83348389ef0bf9

**Comment by PedroFerreiradaCosta** [comment]
The scalling of the kernel matrix seems to have done the trick (like Tippings did). The regression is working and when no relevance vectors are taken (only bias), the model seems to follow the mean, as it should.
